#!/usr/bin/env bash
# Install and configure HAproxy on load balancer

# Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Ensure the /etc/haproxy directory exists
sudo mkdir -p /etc/haproxy
sudo mkdir -p /etc/haproxy/errors

# Overwrite HAproxy config file with a new configuration
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 279806-web-01 18.208.106.131:80 check
    server 279806-web-02 54.235.229.175:80 check
EOL

# Set correct permissions for the configuration file
sudo chown -R haproxy:haproxy /etc/haproxy
sudo chmod -R 755 /etc/haproxy

# Restart HAProxy
sudo systemctl restart haproxy

# Check HAProxy status
sudo systemctl status haproxy
