#!/usr/bin/env bash
# Creates a file contining its PID
# Displays a custom message indefinitely
# Displays a custom message when receiving a SIGTERM signal
# Displays a custom message when receiving a SIGINT signal
# Deletes the file created and terminates
# itself when receiving a SIGQUIT or SIGTERM signal

file="/var/run/myscript.pid"

echo "$$" > $file

trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done

