#!/usr/bin/env bash
# Manages the `manage_my_process` script

handle_start()
{
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
}

handle_stop()
{
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}

handle_restart()
{
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process restarted"
}

if [ $1 = "start" ]; then
	handle_start
elif [ $1 = "stop" ]; then
	handle_stop
elif [ $1 = "restart" ]; then
	handle_restart
else
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
fi
