#!/usr/bin/env bash
# Bash script that displays the content of the file "/etc/passwd"

target_file="/etc/passwd"

while read -r line
do
	username=$(echo "$line" | cut -d: -f1)
	userID=$(echo "$line" | cut -d: -f3)
	homedir=$(echo "$line" | cut -d: -f6)

	echo "$username:$userID:$homedir"
done < $target_file

