#!/usr/bin/env bash
# Bash script that displays the content of the file
# /etc/passwd, using the while loop + IFS

while IFS=: read -r username x userID groupID _ homedir shell
do
	echo "The user $username is part of the $groupID gang, lives in $homedir and rides $shell. $userID place is protected by the passcode $x, more info about the user here: $username"

done < /etc/passwd
