#!/usr/bin/env bash
# Bash script that displays the visitor IP
# along with the HTTP status code from the Apache log file

file="apache-access.log"

awk '{ match($0, /^([^ ]+)/, ip); match($0, /" [0-9]{3}/, status); print ip[0], substr(status[0], 2) }' "$file"
