#!/usr/bin/env bash
# Bash script that displays the content of the
# current directory in a list format

for item in ./*
do
	item_name="${item##./}"

	if [[ "$item_name" == *-* ]]; then
		new_name="${item#*-}"
		echo "$new_name"
	else
		echo "$item_name"
	fi
done
