#!/usr/bin/env bash
# Bash script that displays the content of the
# current directory in a list format

for item in $(ls -1)
do
	if [[ "$item" == *-* ]]; then
		new_name="${item#*-}"
		echo "$new_name"
	else
		echo "$item"
	fi
done
