#!/usr/bin/env bash
# Configure the IP for localhost and Facebook

cp /etc/hosts ~/hosts.new
echo "127.0.0.2\tlocalhost" > ~/hosts.new
echo "8.8.8.8\tfacebook.com" > ~/hosts.new
cp ~/hosts.new /etc/hosts

